<?php

namespace EtudiantBundle\Repository;

/**
 * BaccalaureatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaccalaureatRepository extends \Doctrine\ORM\EntityRepository
{
}
